### ISSUE TITLE
New license request: Unicode-3 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2105] opened 2023-08-31 14:30 UTC
**1.** License Name: Unicode License v3
**2.** Short identifier: Unicode-3
**3.** License Author or steward: Unknown
**4.** Comments: The license is presented in pypi package. Found during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/314
**5.** License Request Url: http://tools.spdx.org/app/license_requests/283
**6.** URL(s): https://www.unicode.org/license.txt
**7.** OSI Status: Pending
**8.** Example Projects: https://www.unicode.org

**Comment by xsuchy** [comment] 2023-08-31 14:31
Text of the license:
```
UNICODE LICENSE V3

COPYRIGHT AND PERMISSION NOTICE

Copyright © 1991-2023 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.

IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.
```

**Comment by xsuchy** [comment] 2023-08-31 14:33
Relevant OSI discussion: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-August/005404.html

**Comment by McCoySmith** [comment] 2023-09-08 17:53
One slight comment on Unicode 3 (full disclosure: I helped draft it and have submitted it to OSI for approval; it is still in the OSI discussion loop as part of the approval process).
The canonical version (which I think is the version SPDX should be using here) uses the generic attribution notice:

Copyright © <YEAR(S)> <COPYRIGHT HOLDER>

The version you have linked to is the one that Unicode is using for its own code, in which they have inserted their own copyright notice:

Copyright © 1991-2023 Unicode, Inc.

So I’d suggest using the former, rather than the latter, for SPDX.

For anyone wanting to review that license (don’t think I can as it’s a bit of a conflict), I circulated on the mailing list a redlined version of the new v3 license versus the old version (the 2015 version, there’s a 2016 version that didn’t go through OSI) with the (somewhat unwieldy) SPDX identifier of https://spdx.org/licenses/Unicode-DFS-2015.html

**Comment by jlovejoy** [comment] 2023-09-09 03:07
Thanks for the update @McCoySmith ! 

So, has the OSI accepted this already or is it still under review?  If the latter, we usually wait until it's been accepted there and then add it here (OSI acceptance = automatic inclusion on SPDX License List)

As for id - seems like `Unicode-3.0` would make sense as this one actually has a version number (thank you!) - the lack of versioning in the past is what resulted in the unwieldy ids previously :)

**Comment by McCoySmith** [comment] 2023-09-09 03:10
Still awaiting OSI approval.
Maybe just hold off on SPDX until that happens?
Unicode-3.0 would work although license doesn’t use the decimal

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by richardfontana** [comment] 2023-09-11 02:05
The problem with SPDX holding off is that Fedora (and downstream derivatives of Fedora using SPDX identifiers) will likely need an SPDX identifier far in advance of OSI making its decision. Of course Fedora could use a `LicenseRef-` and later replace it with whatever identifier SPDX ends up adopting. But is there really a problem with SPDX making a decision in advance of the OSI? It seems `Unicode-3.0` is foreseeably what SPDX would end up using, even in the event that OSI never approves the license. The only possible problem would be OSI insisting on some changes to the license text and Unicode using the same version number for the revised version.

**Comment by juhp** [comment] 2023-09-12 11:50
(Just noting this is _slightly_ similar to [Unicode-DFS-2016](https://spdx.org/licenses/Unicode-DFS-2016.html), but presumably SPDX would consider this to be a different separate license.)

**Comment by richardfontana** [comment] 2023-09-12 13:54
Indeed this is a pretty close match to `Unicode-DFS-2016` such that SPDX could probably deal with it by revising the markup of the latter, but I guess since it's been submitted for OSI approval it's being handled as a special case?

**Comment by jlovejoy** [comment] 2023-09-14 03:18
good catch @juhp and @richardfontana - the only differences b/w this v3 and `Unicode-DFS-2016` are the presence of the name Unicode in a couple places and the defined terms repeated in the top section - in any case, these are not substantive differences as far as SPDX matching guidelines (which it would be really nice if the OSI adopted, as I have previously suggested to the OSI boar :))

Given this, we'd use the same id `Unicode-DFS-20161 and add markup to the existing license and add that it's been OSI-approved.

While I realize this id may not be "desirable" - it was the only way we had to differentiate the license at the time it was submitted to SPDX (which was version 2.6 of the SPDX License List)

While it seems as though Unicode is making minor updates to the license to make it more re-usable - that's great, but it doesn't change the existence of `Unicode-DFS-2016` as far as I can tell.

Of course, if during the OSI process, the text is changed to be substantially different than `Unicode-DFS-2016`, then that would be a different consideration.

(note, we have an open issue as to some other slight variations at #1853 )

tagging @pchestek @webmink and @smaffulli for awareness

**Comment by jlovejoy** [comment] 2023-09-14 03:19
see 
<img width="824" alt="image" src="https://github.com/spdx/license-list-XML/assets/5048659/050534bd-860c-432a-860f-1081fe1e1f86">

and

<img width="734" alt="image" src="https://github.com/spdx/license-list-XML/assets/5048659/03cac666-3c94-4c0f-9de6-3f5a4d51107c">

**Comment by jlovejoy** [comment] 2023-09-14 03:22
as per our https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/ - the inclusion of `("SOFTWARE")` in the Notice section and instances of `the Unicode` and `Unicode` in the grant section could be considered optional

and `UNICODE INC'S DATA FILES ("DATA FILES")` would be marked as replaceable with `DATA FILES`

**Comment by juhp** [comment] 2023-09-14 04:04
Thanks @jlovejoy and @richardfontana 

Yea I agree - personally I would prefer to see the tag `Unicode-DFS-2016` deprecated in favor of `Unicode-3`,
but that is probably a consideration after OSI approval. Conversely perhaps `Unicode-DFS-2016` could be used
in the meantime for this?

**Comment by McCoySmith** [comment] 2023-09-14 04:34
One possibly substantive difference (accounting for the omitable and replacable text designations on Unicode-DFS-2016) is the placement of the “COPYRIGHT AND PERMISSON NOTICE” in v3 is at the top of the license rather than underneath the  Notice to User. This effects a slight substantive change as to what must be reproduced with copies or documentation.

Also, Unicode-DFS-2016 in SPDX still shows a few instances of the word “Unicode” in the text of the license that not in red, thus indicating that it is not replaceable text. I’m assuming perhaps that was an oversight in entry of the license into SPDX? Otherwise, Unicode-DFS-2016 license is only useable by Unicode for Unicode software and data (since the definition of Data Files and Software is “Unicode Inc.’s”). Taking that out was also a substantive change relative to the OSI version of 2015.

 

FWIW, I think Unicode would prefer not to have this new license not be called just an insubstantial variant of Unicode-DFS-2016, but to get a new designation for it. TBH, it seems like the case for insubstantial variation is much better between Unicode-DFS-2015 & Unicode-DFS-2016 since there is but a single line of text (“See Terms of Use for definitions of Unicode Inc.'s Data Files and Software.”) added to 2016; otherwise 2016 & 2015 are, as far as I can tell, identical.

**Comment by jlovejoy** [comment] 2023-09-15 00:00
Re: the difference b/w `Unicode-DFS-2015` and `Unicode-DFS-2016` - the former has an obligation to provide notification in modified files in section (c), which is not present in `Unicode-DFS-2016` - so that is a substantive difference in terms of legal obligations.

There is currently no "replaceable" markup on the Unicode name in `Unicode-DFS-2016` because we generally don't add such markup unless or until we find an actual need and example of such use. We would add it now.

I'm not sure moving "COPYRIGHT AND PERMISSION NOTICE" to a difference location is substantive, as that is like a heading, but I'd want to hear other SPDX-legal thoughts on that.

Do remember: we try to not deprecate or change SPDX license ids unless it is imperative. I'm not sure "would prefer a different id" is imperative. Having two licenses listed with different ids that are the same text (as per SPDX matching guidelines) has happened, I believe one such example was due to some early OSI-approval of two license with different names but had the same text in the early days of "vanity" licenses. But I'd think no one wants to repeat that now :)

**Comment by McCoySmith** [comment] 2023-09-15 17:30
Interesting. 

So the Unicode-DFS-2015 text that SPDX has includes a section (c), but the currently-OSI-approved license doesn’t have that section https://opensource.org/license/unicode-inc-license-agreement-data-files-and-software/ (nor does it have the “See Terms of Use for definitions of Unicode Inc.'s Data Files and Software” of Unicode-DFS-2016). OSI does identify its approved version as Unicode-DFS-2015 under SPDX which seems like it’s inaccurate given the discrepancy (which I hope we’d agree is substantive). I suspect there was a version that existed before submission to OSI that had section (c), that’s the one that got the SPDX identifier, and then it was revised to remove (c) and submitted to OSI, and OSI just assumed the Unicode-DFS-2015 identifier corresponded to the version they approved.

Anyway, a bit of a mess. Probably ought to do some cleanup on it, maybe after deciding on a tag for the new license.

**Comment by xsuchy** [comment] 2023-09-29 14:55
I read all the comments above, but I am not sure I get the conclusion. Do we want create new id and new file? Or edit `Unicode-DFS-2016`?

**Comment by jlovejoy** [comment] 2023-09-30 00:42
> Interesting. So the Unicode-DFS-2015 text that SPDX has includes a section (c), but the currently-OSI-approved license doesn’t have that section https://opensource.org/license/unicode-inc-license-agreement-data-files-and-software/ (nor does it have the “See Terms of Use for definitions of Unicode Inc.'s Data Files and Software” of Unicode-DFS-2016). OSI does identify its approved version as Unicode-DFS-2015 under SPDX which seems like it’s inaccurate given the discrepancy (which I hope we’d agree is substantive). I suspect there was a version that existed before submission to OSI that had section (c), that’s the one that got the SPDX identifier, and then it was revised to remove (c) and submitted to OSI, and OSI just assumed the Unicode-DFS-2015 identifier corresponded to the version they approved. Anyway, a bit of a mess. Probably ought to do some cleanup on it, 

good catch, yeah, I'll try to look into after this release :)

back to the issue at hand - @McCoySmith - how confidant are you that the text as shown at https://www.unicode.org/license.txt is stable and very, very, very unlikely to change in the OSI-approval process?  (from my fuzzy recollection, I think that URL has had that text published for some time now?)  Reason asking if: we are inclined to simply give this a new identifier of `Unicode-3.0` and then add a note describing the similarities with `Unicode-DFS-2016` but the only reason to hold-off would be on the chance the text ended up changing...

**Comment by McCoySmith** [comment] 2023-09-30 04:18
Very unlikely it will change. Submitted to OSI a while back, no substantive comments, its been through multiple levels of review. Safest bet it to wait for OSI approval, but if you need to approve before that given it has been already submitted to SPDX I think you are pretty safe.

 

From: Jilayne Lovejoy ***@***.***> 



back to the issue at hand - @McCoySmith <https://github.com/McCoySmith>  - how confidant are you that the text as shown at https://www.unicode.org/license.txt is stable and very, very, very unlikely to change in the OSI-approval process? (from my fuzzy recollection, I think that URL has had that text published for some time now?) Reason asking if: we are inclined to simply give this a new identifier of Unicode-3.0 and then add a note describing the similarities with Unicode-DFS-2016 but the only reason to hold-off would be on the chance the text ended up changing...

**Comment by juhp** [comment] 2023-09-30 05:54
Should we send a mail to Unicode then, to confirm?

**Comment by McCoySmith** [comment] 2023-09-30 05:58
You don’t need to. I wrote the license and submitted it to OSI on their behalf.

**Comment by jlovejoy** [comment] 2023-10-01 17:10
> Very unlikely it will change. Submitted to OSI a while back, no substantive comments, its been through multiple levels of review. Safest bet it to wait for OSI approval, but if you need to approve before that given it has been already submitted to SPDX I think you are pretty safe.

Thanks @McCoySmith - I also realized that this new text was raised back in Feb in #1851 (which I just closed since we have this issue going). 

Using the Wayback machine, it appears that at the URL https://www.unicode.org/license.txt :
- as of Feb 16, 2023 - the text was still a match to `Unicode-DFS-2016` up until Sept 11, 2023 when it shows the text changed to the OSI submission and version number added. This is a bit odd as the Feb issue here talks about how the license text had changed at that url back then.  
- I also realized I had reached out to Unicode based on some minor variations of `Unicode-DFS-2016` found "in the wild' - such variations were about the inclusion or omission of the NOTICE paragraph which made us/SPDX wonder if we ought to mark that as optional. I don't know if there was a clear answer to that, as I think it may have been a scenario of someone applying the license in a sloppy way
- In any case, it's helpful that the current text at that same URL is now versioned, something I hope Unicode continues to do. It's also be great if any subsequent versions don't use the same URL :)

As to adding this now or waiting for the OSI to officially approve, I may just make the PR but hold off on merging it until that point.

**Comment by jlovejoy** [comment] 2023-10-04 18:03
the x.y versioning is documented here: https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md and been in place since ~2010 and the first release of the SPDX License List

BSD-3-clause is descriptive of the # of clauses, not the license version.

Yes, that Unicode didn't version previous licenses AND updated the same URL with no way to know when that was changed (and Unicode is not alone in doing this, to be fair) has caused a lot of unnecessary work .  I don't really see why 3.0 is an issue - maybe they don't think they'll do a dot release, but it leaves the option open and conforms to SPDX License List since its inception.

**Comment by penguinpee** [comment] 2023-10-04 23:14
Chiming in here as I just submitted [pyuca](https://github.com/jtauber/pyuca) for [review](https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2242026) in Fedora. That has the following text in [`LICENSE-allkeys`](https://raw.githubusercontent.com/jtauber/pyuca/v1.2/LICENSE-allkeys) (re-wrapped for better readability):

```
Copyright © 1991-2013 Unicode, Inc. All rights reserved. Distributed
under the Terms of Use in http://www.unicode.org/copyright.html.

Permission is hereby granted, free of charge, to any person obtaining a
copy of the Unicode data files and any associated documentation (the
"Data Files") or Unicode software and any associated documentation (the
"Software") to deal in the Data Files or Software without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, and/or sell copies of the Data Files or Software,
and to permit persons to whom the Data Files or Software are furnished
to do so, provided that (a) the above copyright notice(s) and this
permission notice appear with all copies of the Data Files or Software,
(b) both the above copyright notice(s) and this permission notice
appear in associated documentation, and (c) there is clear notice in
each modified Data File or in the Software as well as in the
documentation associated with the Data File(s) or Software that the
data or software has been modified.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR
ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR
SOFTWARE.

Except as contained in this notice, the name of a copyright holder
shall not be used in advertising or otherwise to promote the sale, use
or other dealings in these Data Files or Software without prior written
authorization of the copyright holder.
```

That differs from the text in https://github.com/spdx/license-list-XML/issues/2105#issuecomment-1701165975

However the [files](https://github.com/jtauber/pyuca/tree/v1.2/pyuca) this license applies to have different headers. The most recently added files (`allkeys-9.0.0.txt` and `allkeys-10.0.0.txt`) have a header of the form:

```
# allkeys-10.0.0.txt
# Date: 2017-04-26, 11:47:03 GMT [KW]
# Copyright 2017 Unicode, Inc.
# For terms of use, see http://www.unicode.org/terms_of_use.html
```

The mentioned URL redirects to https://www.unicode.org/copyright.html, which mentions [Unicode Data Files and Software License](https://www.unicode.org/license.txt), which is the license text under review here.

The dates differ per file. However, since they all refer to the same URL, I assume the same, most recent version of the license applies.

**Comment by jlovejoy** [comment] 2023-11-28 22:46
@McCoySmith - can you confirm this did get OSI approved and the text has not changed?

**Comment by McCoySmith** [comment] 2023-11-29 00:13
1.	Not yet OSI approved, but scheduled to be voted on at next OSI board meeting which is, I think, next month.
2.	No changes to license; I don’t anticipate any as there were no substantive comments on the license-approval mailing list.

 

I’d suggest you wait til EOY then finalize; I’ll notify you when I hear about OSI approval (which I anticipate will occur given no substantive objections on the mailing list)

**Comment by richardfontana** [comment] 2023-11-29 04:21
It is now OSI-approved (assuming they approved the same license we're talking about here):
https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-November/005448.html

**Comment by penguinpee** [comment] 2023-11-29 08:14
Hooray! Now I hope this license applies to `pyuca` (https://github.com/spdx/license-list-XML/issues/2105#issuecomment-1747772488) as well. :crossed_fingers:

**Closed** 2024-01-02 18:01 UTC
Labels: new license/exception request, new license/exception: Accepted, new license/exception: waiting for steward, used in major distro
