### ISSUE TITLE
New license request: Hippocratic-3.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1392] opened 2022-01-06 17:02 UTC
**1.** License Name: Hippocratic License 3.0
**2.** Short identifier: Hippocratic-3.0
**3.** License Author or steward: @EthicalSource on GitHub
**4.** Comments: 
**5.** Standard License Header: There is no standard header for this license
**6.** License Request Url: http://tools.spdx.org/app/license_requests/137
**7.** URL(s): 
**8.** OSI Status: Not Submitted
**9.** Example Projects: http://tidyblocks.tech/, https://github.com/vcr/vcr

**Comment by swinslow** [comment] 2022-01-06 17:42
duplicate of #1393, closing this and can discuss in #1393

**Closed by swinslow** 2022-01-06 17:42 UTC

**Comment by Tyler887** [comment] 2022-01-06 17:49
> duplicate of #1393, closing this and can discuss in #1393

Don't worry! I just ended up thinking there was a **bug** on the online tools website, but it was actually not.
