### ISSUE TITLE
GNU Free Document Licence with no Invariant Sections

### ISSUE THREAD

**Issue by mchehab** [spdx/license-list-XML#686] opened 2018-08-30 15:33 UTC
Several old documentation files were written using GFDL licence, with was, on that time, believed to be a free license. However, a more modern read of the license considers it non-free, if an optional "Invariant Sections" part of the license is used. As a reference, see: https://www.debian.org/vote/2006/vote_001

Currently, at https://spdx.org/licenses/, it is only possible to state that a document follows FDL (for example, using SPDX identifier GFDL-1.1-or-later), but currently ther's no way to distinguish between a GFDL with Invariant Sections from a GFDL without it. As explained at: https://spdx.org/licenses/GFDL-1.1-or-later.html ADDENDUM, the files licensed under GFDL that doesn't use Invariant Sections should follow this rule:

	'If you have no Invariant Sections, write "with no Invariant 
	 Sections" instead of saying which ones are invariant. If you
	 have no Front-Cover Texts, write "no Front-Cover Texts"
	 instead of "Front-Cover Texts being LIST"; likewise for
	 Back-Cover Texts.'

So, IMHO, in order to be able to use SPDX without those optional parts of the spec, specially the Invariant Sections, an exception is needed. e. g. something like:

	'Permission is granted to copy, distribute and/or modify this document under
	 the terms of the GNU Free Documentation License; with no Invariant Sections,
	 no Front-Cover Texts and no Back-Cover Texts.'

**Comment by jlovejoy** [comment] 2018-09-20 16:57
began to look at on Sept 20 call, but more involved issue that will need more discussion

**Comment by swinslow** [comment] 2018-11-01 17:10
I'm not yet that familiar with how the GFDL family of licenses are used in practice. 

That said, I'm inclined to say that I'm not sure this necessarily calls for a change to the SPDX license identifiers or license list. The identifier `GFDL-1.1-or-later`, for instance, can be used in SPDX documents or short-form identifiers, to denote that documentation is subject to the GFDL version 1.1 (or later). 

That identifier might not provide 100% of the information that might be needed to comply with the license. But I think that's the case for many licenses (such as those where the licensor could e.g. specify a proxy to make decisions about future license versions; or in a sense, even copyright statements and the like that need to be reproduced). For purposes of using SPDX, the identifier enables distributors and users to know that the license is present and/or applies, even if one might need additional information to fulfill their compliance obligations.

That's my initial gut reaction, though, and again I'm still new to how GFDL is used in practice...

**Comment by mchehab** [comment] 2018-11-18 13:59
> I'm not yet that familiar with how the GFDL family of licenses are used in practice.
> 
> That said, I'm inclined to say that I'm not sure this necessarily calls for a change to the SPDX license identifiers or license list. The identifier `GFDL-1.1-or-later`, for instance, can be used in SPDX documents or short-form identifiers, to denote that documentation is subject to the GFDL version 1.1 (or later).
> 
> That identifier might not provide 100% of the information that might be needed to comply with the license. But I think that's the case for many licenses (such as those where the licensor could e.g. specify a proxy to make decisions about future license versions; or in a sense, even copyright statements and the like that need to be reproduced). For purposes of using SPDX, the identifier enables distributors and users to know that the license is present and/or applies, even if one might need additional information to fulfill their compliance obligations.
> 
> That's my initial gut reaction, though, and again I'm still new to how GFDL is used in practice...

GFDL is very different than another license that would for example require a proxy. It somewhat resembles CC, in the sense of, depending if it has invariant sections or not, it can either be a free or non-free license.

So, for someone running a software that would check if the license matches the distribution requirements, it has to have an unique way to distinguish between the free and non-free versions of it.

See Debian analysis about this license:
     https://www.debian.org/vote/2006/vote_001

**Comment by jlovejoy** [comment] 2018-12-13 18:45
thanks for the above comment! 
this got back-burnered again by other distractions, so moving to next release. Let's try to prioritize early in that release cycle to find some resolution here.

**Comment by swinslow** [comment] 2019-01-24 17:44
Discussed on 2019-01-24 call; want to discuss with broader group on next call re: whether to include separate IDs for different implementations of same license text; how this interacts with concept of exceptions; etc.

**Comment by swinslow** [comment] 2019-03-21 17:07
This request was discussed on 2019-03-21 legal team call. Consensus was not yet reached on whether to add this as separate licenses from GFDL-1.1[-only/-or-later], and more discussion was desired. The team's intention is to dedicate more time for analyzing this on the next legal team call on 2019-04-04, with the aim of making a yes-or-no decision then.

**Comment by swinslow** [comment] 2019-07-27 18:48
Circling back on this issue which has languished for a while (apologies!) -- would really like to address this one in 3.7.

Having recently learned more about the GFDL and how it's intended to be used, I understand the request better now. I now disagree with my own earlier comments in this thread  =)

I do think it makes sense to be able to express in SPDX license identifiers whether or not there are invariant sections / cover texts.

The correct mechanics though are a bit unclear to me. Here's the questions I'm currently wondering:

1) **What should a default "GFDL-1.3-[only/or-later]" tag mean?** Looking at the text of GFDL-1.3, I read it to say that there are by default no Invariant Sections or Cover Texts _unless_ the licensor explicitly states that there are, in the license notice. That makes me think that the default GFDL-1.3 case should mean "no invariant sections and no cover texts", and there should be a different license ID (_not_ an exception) to be used when there are invariants / cover texts.

2) **However it works, can we combine invariants + cover texts in one identifier?** Regardless of the answer to 1, I'm hoping we can avoid too many different combinations of license or exception identifiers. Particularly since we're already splitting these by "-only" and "-or-later". Would it be generally suitable to have two identifiers, one meaning "no invariants OR cover texts" and the other meaning "invariants OR cover texts"? In the latter case, it would signal that one or the other is present, and the licensee could then read the applicable notice to figure out which ones specifically.

3) **Is this also applicable to GFDL-1.1 and -1.2?** It looks to me like it is, though possibly -1.1 handles the "default" position differently; I'm not clear whether that's the intent.

**Comment by mchehab** [comment] 2019-07-27 19:26
> I do think it makes sense to be able to express in SPDX license identifiers whether or not there are invariant sections / cover texts.

Talking only as a developer that has being doing development for a while: yeah, I think we need to be explicit about whether or not invariant parts are there.

In the past, most OSS developers didn't really understand those invariant texts. They used to release docs publicly using GFDL because it was believed to be free.  So, I *suspect* that most projects with use GFDL don't have invariant parts (although I guess GNU uses invariant parts on some projects hosted there).

> The correct mechanics though are a bit unclear to me. Here's the questions I'm currently wondering:
> 
>     1. **What should a default "GFDL-1.3-[only/or-later]" tag mean?** Looking at the text of GFDL-1.3, I read it to say that there are by default no Invariant Sections or Cover Texts _unless_ the licensor explicitly states that there are, in the license notice. That makes me think that the default GFDL-1.3 case should mean "no invariant sections and no cover texts", and there should be a different license ID (_not_ an exception) to be used when there are invariants / cover texts.

That was my past understanding too, but I was pointed by a distro developer that wanted to ship Kernel documentation that GFDL says that documents with no invariant sections/cover texts should explicitly say so at their licensing text. 
I double-checked and indeed the license text says so. So, on Linux Kernel, we ended by explicitly stating that.

>     2. **However it works, can we combine invariants + cover texts in one identifier?** Regardless of the answer to 1, I'm hoping we can avoid too many different combinations of license or exception identifiers. Particularly since we're already splitting these by "-only" and "-or-later". Would it be generally suitable to have two identifiers, one meaning "no invariants OR cover texts" and the other meaning "invariants OR cover texts"? In the latter case, it would signal that one or the other is present, and the licensee could then read the applicable notice to figure out which ones specifically.

I suspect that, for all practical effects, for a given GFDL variant, there are just two distinctions:

- A "free" GFDL doesn't contain any invariant part;
- A "non-free" GFDL, contains either invariant sections or invariant cover texts (or both).

I mean, if someone is checking what licences are used on a project, the only thing that matters is to be sure that all GFDL files are "free" or not. If not "free", it doesn't really matter what part of the doc is invariant (cover, back-cover and/or sections).

>     3. **Is this also applicable to GFDL-1.1 and -1.2?** It looks to me like it is, though possibly -1.1 handles the "default" position differently; I'm not clear whether that's the intent.

I suspect that the same applies for 1.1 and 1.2. I would add a different SPDX mark if it is either "free" or "non-free".

**Comment by mchehab** [comment] 2020-06-16 07:18
As mentioned on #970, the legal team seemed to opt creating a different SPDX header for each variant. In the case of the Linux Kernel (whose was the primary reason for opening this issue), we only use GFDL 1.1+ and GFDL 1.2+. So, this should be enough for its needs:

- GFDL-1.1-or-later-no-invariant
- GFDL-1.2-or-later-no-invariant

**Comment by swinslow** [comment] 2020-06-16 13:05
Thanks @mchehab -- yes, based on the outcome of the discussion in #970 last month we decided that these should have separate IDs. I'll get these two queued up and will aim to have them merged following the next legal team call this Thursday 2020-06-18.

They won't officially appear on the [license list website](https://spdx.org/licenses) until the 3.10 release at the end of July, but typically we've seen people start using the IDs once they have landed in the master branch, so hopefully that won't hold you up.

Thanks for your patience, I know this one has been open/pending for a very long time.

**Closed** 2020-07-02 16:06 UTC
Labels: discuss on legal call

**Comment by swinslow** [comment] 2020-07-02 16:53
Hi @mchehab, these have all now been merged into the main branch. As mentioned above they won't show up on the license list website until the 3.10 release (likely end of July) but the identifiers are fine to use now.

As we discussed in the PR thread (just recording here for visibility) the identifier format was switched to put the `-or-later` at the end, so the identifiers I think you'll be using are:
- GFDL-1.1-no-invariants-or-later
- GFDL-1.2-no-invariants-or-later

Thanks again for your patience with us in getting these added to the list.

**Comment by swinslow** [comment] 2020-08-07 15:25
Hi @mchehab, just circling back to let you know that the 3.10 version of the license list has been released, so these identifiers are now present on the published site at https://spdx.org/licenses:

- [GFDL-1.1-no-invariants-or-later](https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.html)
- [GFDL-1.2-no-invariants-or-later](https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.html)

**Comment by mchehab** [comment] 2020-08-26 07:29
> Hi @mchehab, just circling back to let you know that the 3.10 version of the license list has been released, so these identifiers are now present on the published site at https://spdx.org/licenses:
> 
>     * [GFDL-1.1-no-invariants-or-later](https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.html)
> 
>     * [GFDL-1.2-no-invariants-or-later](https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.html)

Thanks!

Just submitted upstream the Linux Kernel patches to use those.
