### ISSUE TITLE
New license request: ASWF Digital Assets License 1.0

### ISSUE THREAD

**Issue by zvr** [spdx/license-list-XML#1550] opened 2022-08-03 14:25 UTC
- Full name: ASWF Digital Assets License version 1.0
- Short identifier: ASWF-Digital-Assets-1.0
- Other web pages for license/exception: https://github.com/AcademySoftwareFoundation/foundation/tree/main/digital_assets
- Notes:
- OSI Approved:
- FSF Free/Libre:
- Text:

ASWF Digital Assets License v1.0

License for <Asset Name> (the “Asset Name”).

<Asset Name> Copyright <Year> <Asset Owner>. All rights reserved.

Redistribution and use of these digital assets, with or without modification, solely for education, training, research, software and hardware development, performance benchmarking (including publication of benchmark results and permitting reproducibility of the benchmark results by third parties), or software and hardware product demonstrations, are permitted provided that the following conditions are met:

1. Redistributions of these digital assets or any part of them must include the above copyright notice, this list of conditions and the disclaimer below.

2. Publications showing images derived from these digital assets must include the above copyright notice.

3. The names of copyright holder or the names of its contributors may NOT be used to promote or to imply endorsement, sponsorship, or affiliation with products developed or tested utilizing these digital assets or benchmarking results obtained from these digital assets, without prior written permission from copyright holder.

4. The assets and their output may only be referred to as the Asset Name listed above, and your use of the Asset Name shall be solely to identify the digital assets. Other than as expressly permitted by this License, you may NOT use any trade names, trademarks, service marks, or product names of the copyright holder for any purpose.

DISCLAIMER: THESE DIGITAL ASSETS ARE PROVIDED BY THE COPYRIGHT HOLDER “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THESE DIGITAL ASSETS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by swinslow** [comment] 2022-08-05 13:53
Thanks for submitting this @zvr!

I was involved with the development of this license while I was at the LF, so I'm going to refrain from being a +1 or -1 on adding this. Writing here to provide some additional context:

This license was developed by the [Academy Software Foundation (ASWF)](https://www.aswf.io) community. All of the software that ASWF develops is [open source](https://github.com/AcademySoftwareFoundation).

The Digital Assets License submitted here was developed to be used for publicly sharing motion picture assets, such as extremely large data sets for 3D modeling. The license was intentionally drafted to permit broad redistribution, modification and use, but _not_ for all production purposes, rather for the subset of purposes listed in the license grant language at the top. In this way I wouldn't expect that it meets the full "open content" requirements for most such definitions, but may be appropriate to add on the basis of the other inclusion principles.

There's a blog post [here](https://linuxfoundation.org/blog/academy-software-foundation-giving-open-communities-access-to-production-grade-digital-assets-for-testing-demonstration-and-education-purposes/) which gives some more details on the context.

**Comment by jlovejoy** [comment] 2022-08-11 15:27
# New submission review

## Has the license been approved by the OSI?
does not seem so

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?
it is unique

### If a software license, does it apply to source code and not only to executables?
more of a content or data license than for software

### Does the license have identifiable and stable text, and is not in the midst of drafting?
yes, seems stable

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?
yes

## Other factors for inclusion

### 1. Does the license substantially comply with one of the free/open content definitions?
I'd say so. The requirement to use a specific name in clause 4 has been historically been seen by some to be a restriction and therefore make a license non-free, but for our purposes here, I don't think that is grounds for exclusion.

### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?
ye

### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
I'm unclear as to actual use

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?
Yes

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?
yes

## Summary of factors / outcome
I'm in favor of addition, pending some examples of actual use

**Comment by swinslow** [comment] 2022-08-11 18:27
@jlovejoy Thanks -- on the review, I feel like I should note that the license grant language in the preamble is limited to only certain permitted uses. That may affect your view on the first "other factor".

**Comment by jlovejoy** [comment] 2022-08-16 05:29
thanks @swinslow - I somehow read that initially and then "skipped" it when I re-read and did the review!

Here's a do-over on a couple of the factors:

1. Does the license substantially comply with one of the free/open content definitions?
Not really due to the usage restriction to "solely for education, training, research, software and hardware development, performance benchmarking (including publication of benchmark results and permitting reproducibility of the benchmark results by third parties), or software and hardware product demonstrations, . . ."

Also, the requirement to use a specific name in clause 4 has been historically been seen by some to be a restriction and therefore make a license non-free, but for our purposes here, I don't think that is grounds for exclusion.

4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?
I'd still say yes, as the allowable "solely for" uses cover a range of uses

still need more info as actual use (#3) - @zvr - do you have any insight as to that?

**Comment by zvr** [comment] 2022-08-22 14:49
@jlovejoy all the content by ASWF is under this license (actually, its current version).
See https://dpel.aswf.io/ ; for example, https://dpel.aswf.io/asc-stem2/

**Comment by jlovejoy** [comment] 2022-08-31 04:50
I revised my review above.

**Comment by bsdimp** [comment] 2022-11-29 17:18
+1 for inclusion, since it is open source or open source adjacent. Since it doesn't apply 100% to code, but rather data, I think it's OK since the clear guidelines for what is 'open source' don't yet have a clear analog for 'open data' though many standards are competing today...  I think that the restrictions wouldn't unduly interfere with its basic use or distribution, but could affected 'derived works', which gives me some pause, but not enough to reject.

**Comment by kestewart** [comment] 2023-04-07 18:41
+1 on including it.

**Comment by jlovejoy** [comment] 2023-04-25 03:57
@BassCoder2808 - do you want to make a PR for the files for this license? Might be a good way to test on a real one ;)

**Comment by BassCoder2808** [comment] 2023-04-25 04:07
Thanks @jlovejoy, sure I would love to make a PR for the same. I will start working on it right away.

**Comment by BassCoder2808** [comment] 2023-04-25 05:59
Hi @jlovejoy, I was making the files for the license, and wanted to ask that for the `canonical text` we should use this link https://github.com/AcademySoftwareFoundation/foundation/tree/main/digital_assets/aswf_digital_assets_license_v1.0.txt correct?
Or is there some other link for the same. Also as this license was submitted through an issue template in GitHub itself, so the field `URL to project(s) that use license` is missing, so what value should I put there?

**Comment by BassCoder2808** [comment] 2023-04-25 16:57
Thanks @jlovejoy for clarification, I will use the text file which you have mentioned above and will start with the XML file creation

**Closed** 2023-05-02 17:46 UTC
Labels: new license/exception request, new license/exception: Accepted
