### ISSUE TITLE
New license request: JPL-image [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mattiaverga** [spdx/license-list-XML#1734] opened 2022-12-07 08:25 UTC
**1.** License Name: JPL Image Use Policy
**2.** Short identifier: JPL-image
**3.** License Author or steward: Unknown
**4.** Comments: This has been allowed in Fedora for many years
**5.** License Request Url: http://tools.spdx.org/app/license_requests/190
**6.** URL(s): https://www.jpl.nasa.gov/jpl-image-use-policy
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/CelestiaProject/CelestiaContent

**Comment by richardfontana** [comment] 2022-12-09 05:05
Note, this arises out of a [Fedora packaging issue](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/107), and Fedora has approved this license (though will possibly restrict the approval to the "allowed-content" category), so Fedora considers it high priority.

**Comment by swinslow** [comment] 2022-12-09 15:00
Short version, I'm a cautious +1 to add, primarily driven by its approval for use in Fedora. Here are my thoughts on this one, based on the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md). 

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [x] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [x] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [x] Yes => N/A, this is an image use license (styled as a "policy"), not a software license
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [x] Yes => apparently has been stable since at least 2020
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No
Not clear. JPL is presumably the "steward" insofar as this is their image use policy. It looks like the version [used in Celestia](https://src.fedoraproject.org/rpms/celestia/blob/rawhide/f/README-LEGAL.JPL) and pulled in July 2020 is identical to the version on JPL's website as of Dec. 2022. 

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [x] Yes => Although this is framed as a website download 'policy', and setting aside the "Special Cases" addendum, the primary part is essentially an attribution-style permissive license to use for any purpose. As noted above, Fedora has also approved this license.
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [x] No => This is solely intended for material published by JPL
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [x] Yes => Used for JPL images, including in the Celestia project in Fedora as described above
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [x] Yes => See above re: substantially complying with open content permissions
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [x] No => unknown but doubt it

## Summary of factors, outcome, comments

Although this feels weird to approve given that it's framed as a website download 'policy', I think that the nature of it as granting a permission to use the JPL images for any purpose is sufficient to warrant inclusion, when tied together with its use for content in Fedora.

**Comment by jlovejoy** [comment] 2022-12-21 23:17
agreed @swinslow - it's a bit odd, but given people seem to be reproducing it as a license, and that seems to be the intent, I guess I can't get hung up on the name using "policy"

**Closed** 2023-02-12 23:28 UTC
Labels: new license/exception request, new license/exception: Accepted, used in major distro
