### ISSUE TITLE
New license request: BSD-3-Clause-No-Military [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jnordberg** [spdx/license-list-XML#1191] opened 2021-02-15 01:13 UTC
**1.** License Name: BSD 3-Clause No Military
**2.** Short identifier: BSD-3-Clause-No-Military
**3.** License Author or steward: 
**4.** Comments: This license is the same license as BSD-3-Clause, except it specifies that that software is not licensed for use in a military facility.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/99
**7.** URL(s): 
**8.** OSI Status: Not Submitted
**9.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/56db62be-fbf8-4d44-a5ea-993558690dfe.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause-No-Nuclear-License-2014

**Comment by jnordberg** [comment] 2021-02-15 01:16
```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 132, in submitNewLicense matchingIds, matchingType = utils.check_spdx_license(licenseText) File "/spdx/src/app/utils.py", line 531, in check_spdx_license listedLicense = getListedLicense(licenseID) File "/spdx/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 88, in getListedLicense listed_license = licenseinfofactoryclass.getListedLicenseById(licenseId) File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 62, in __call__ raise TypeError("Package {0} is not Callable".format(self.__name)) TypeError: Package org.spdx.rdfparser.license.LicenseInfoFactory.getListedLicenseById is not Callable
```

Encountered an error when submitting this, after trying again it seems to have worked. Some info I entered is missing from this issue though.

Example projects:
 - https://github.com/greymass/anchor-link/blob/master/LICENSE
 - https://gitlab.syncad.com/hive/dhive/-/blob/master/LICENSE

**Comment by swinslow** [comment] 2021-02-16 14:19
cc @goneall, note the error message flagged in the comment above during the license request submission process here.

**Comment by goneall** [comment] 2021-02-16 20:40
@jnordberg thanks for reporting the issue.  I just restarted the server which seems to clear this issue up.

**Comment by bsdimp** [comment] 2021-04-15 17:04
Is this a case where we use the BSD-3-clause license but add a 'with military-prohibition' like we do for gpl with system-call-exception? It otherwise seems like a verbatim text of the BSD-3-clause license (I didn't do a diff to be 100% sure), but the more odd variants that just add text at the end we have seems like a liability that the WITH clause was designed to overcome.

**Comment by swinslow** [comment] 2021-04-16 18:35
Good question, @bsdimp. Typically in the past we have not done that, to add something to the Exception list for use with the WITH clause, where the modification adds a _restriction_ to the scope of the main license. 

The reason for this is that the [SPDX License Exception list](https://spdx.org/licenses/exceptions-index.html) is described on that page as being for things that "grant an exception to a license condition or additional permissions beyond those granted in a license". The idea being, that way, where there's "License WITH Exception", a recipient could rely on being able to ignore the exception and just use it under the base license if they chose. If the right-hand-side of the WITH clause could impose additional restrictions, then that wouldn't be an option.

There have been periodic discussions about changing this, but hasn't been a concrete proposal or full discussion (that I'm aware of) about whether it should be changed.

In light of that, if this one were to be accepted, I'd be inclined to say that it would be as its own standalone license entry on the main [SPDX License List](https://spdx.org/licenses/) -- presumably as another BSD-3-Clause-something variant to join the others...

Given that there are a handful of projects using this in the wild which appear to be unrelated to one another, and that as noted it is highly comparable but not identical to the [`BSD-3-Clause-No-Nuclear-License`](https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html), personally I'm slightly in favor of adding it.

**Comment by jlovejoy** [comment] 2021-04-29 16:36
discussed on April 29 call:
- this license is exactly the same as https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html but for instead of "nuclear facility" v. "military facility" in this license
- discussion about some discomfort at having another license and that has a restriction of use and seemingly only used by one company/a limited number of people 
- to be added b/c it meets inclusion guidelines and due to previous similar being license

**Comment by jlovejoy** [comment] 2021-04-29 16:39
include a note along the lines of https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html

**Comment by capfei** [comment] 2021-04-29 18:45
@jlovejoy After thinking some, would it be preferable to have BSD-3-Clause-No-Nuclear-License-2014 and BSD-3-Clause-No-Nuclear-License turned into templates so one word differences do not need their own entry? 

The difference between No Nuclear License and No Nuclear Warranty is one has the word "licensed" in the last sentence and the other doesn't. 

Same with this: instead of Oracle it has copyright holder and military instead of nuclear.

If it is better, I can open a separate issue for discussion.

**Comment by bsdimp** [comment] 2021-05-01 23:26
I've wanted some way to parameterize license text. In most cases I've wanted this for to date, this can usually be handled by a descriptive word in the license (eg "Author" vs "$COMPANY_NAME_HERE"). This might be one case, however, where that's not sufficient, and an expansion of the standard license identifier expression may be necessary along the lines of  WITH, but using a different word. WITH, as was explained in a prior meeting, is used to add exemptions to compliance to the license (like WITH syscall-exception). Perhaps we need a RESTRICTED-BY phrase for a license that's the same as another license, but with additional terms that are basically additional constraints. the other alternative would be to have some way to insert a single value into the license, but I suspect that would get ugly quickly as people seek to draft licenses that have replaceable bits that might just be better served by having a regular adding restrictions mechanism.

**Comment by jlovejoy** [comment] 2021-05-04 23:35
@capfei , @bsdimp - the use of the "replaceable" text tag as per matching guideline 2.1.3 is for text that is no legally substantive. In this case, the addition of one word, "licensed" is a big difference. Saying:
"You acknowledge that this software is not designed or intended for use in . . ." is kind of like an FYI statement and really emphasizes and provides a specific example to the "as is" and disclaimer of fitness for a particular purpose. I can still use the software for the unintended use, but it's on me.
Contrast, if the software "is not . . .  licensed for use in..." then I simply do not have permission to use it in this case. Because it is the license that gives me permission to use a copyrighted work. 

Now, I wonder about the history of the same license that includes that and omits it as to whether that was even intended, but... that is really here nor there for our work!

**Comment by jlovejoy** [comment] 2021-05-04 23:40
btw, in case anyone was wondering (because I had to stop and look twice) - the difference between https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html and https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html is in the disclaimer paragraph. While similar in terms of what is disclaimed, it was different enough to simply capture as two licenses. :( 

I believe these were added ~v2.5 / 2016 :)

**Comment by jlovejoy** [comment] 2021-05-13 17:47
see #1259 , closing issue, as PR is in process now

**Closed by jlovejoy** 2021-05-13 17:47 UTC
Labels: new license/exception request, new license/exception: Accepted
