### ISSUE TITLE
New license request: TGPPL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2308] opened 2024-01-03 17:18 UTC
**1.** License Name: Transitive Grace Period Public Licence 1.0
**2.** Short identifier: TGPPL-1.0
**3.** License Author or steward: 
**4.** Comments: copied from Fedora wiki page and then put in text editor and converted to plain text
**5.** License Request Url: http://tools.spdx.org/app/license_requests/331
**6.** URL(s): https://fedoraproject.org/wiki/Licensing/TGPPL
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/412

**Comment by swinslow** [comment] 2024-01-18 22:56
@jlovejoy is this a duplicate of #2263?

**Comment by swinslow** [comment] 2024-01-18 23:03
closed / fixed by #2310

**Closed by swinslow** 2024-01-18 23:03 UTC
