### ISSUE TITLE
New license request: Polyform-1.0.0 licenses [EDITED]

### ISSUE THREAD

**Issue by MarkAtwood** [spdx/license-list-XML#885] opened 2019-06-27 15:11 UTC
The https://github.com/polyformproject is a thing, working to develop a CC- like templated source available license set.

We should otherwise avoid assigning license IDs beginning with "PF-" and encourage the Polyform Project to use a prefix of "PF-".

**Comment by jlovejoy** [comment] 2019-06-27 16:04
FYI @heathermeeker

**Comment by kemitchell** [comment] 2019-06-27 17:37
@jlovejoy I think both @heathermeeker and I would prefer `Polyform-`.

We're planning to release 1.0.0 versions of a few licenses on that pattern this weekend. I will handle the PRs here.

**Comment by swinslow** [comment] 2019-08-08 13:34
@kemitchell has added a PR for the Polyform licenses at https://github.com/spdx/license-list-XML/pull/903/files

I'm going to tag this as "discuss on legal call" as it looks to me like each of these is intended to place limits on use, redistribution or both.

**Comment by heathermeeker** [comment] 2019-08-08 15:08
That is correct, Polyform licenses contain license scope limitations.  They are similar, but not identical, to those imposed by Creative Commons NC https://spdx.org/licenses/CC-BY-NC-4.0.html and Creative Commons ND https://spdx.org/licenses/CC-BY-ND-4.0.html. Polyform project is intended, in some measure, to be an analog to Creative Commons for software licenses.

**Comment by pombredanne** [comment] 2019-08-08 17:15
Most proprietary licenses have been not been added in the past on the grounds that they were proprietary or not OSI-approved or not open source-like or were not (yet) used by any open source projects... 

I am all for adding as many licenses to the list as relevant and evolve the ["License Inclusion Principles"](https://spdx.org/spdx-license-list/license-list-overview) accordingly. Yet I am a tad confused of late as to how these principles seem to be evolving tacitly. 

I would be curious to find out if these new licenses meet any or all of the current principles and if yes, if this sets some precedent.

**Comment by swinslow** [comment] 2019-08-08 17:24
Discussed on 2019-08-08 legal team call, with a couple of outcomes: 

1) For this issue specifically, the original question was whether to informally "set aside" a prefix for licenses from Polyform. From this thread it sounds like the preferred prefix would be "Polyform-" rather than "PF-". The legal team agreed that we wouldn't adopt other licenses from unrelated submissions with the prefix "Polyform-".

2) To the broader question about whether these licenses should be added, the discussion on the call circled around the question that has come up (here and for other recent submissions) whether the SPDX license list's License Inclusion Principles should be expanded to explicitly include source-available but clearly non-open-source-ish licenses. 

For 2, the outcome was that there are different views on this question, but agreed that explicitly expanding the scope of the license list inclusion principles goes to the core purpose of the list. And as @pombredanne just noted, this question has come up in several contexts recently and clarity on going-forward approach would be helpful. So it likely warrants a broader and deliberate conversation with the SPDX community outside the scope of just today's call. 

Will be discussing with other SPDX teams whether this can be part of the next general community call or otherwise, but either way, will circle back to this issue thread to highlight so that participants here can join that conversation if they choose.

**Comment by kemitchell** [comment] 2019-08-08 17:27
Thank you for "reserving" the prefix. FWIW, a US trademark application for Polyform is currently pending: https://tsdr.uspto.gov/#caseNumber=88400646&caseType=SERIAL_NO&searchType=statusSearch

**Comment by swinslow** [comment] 2019-12-31 16:37
I've changed the name of this issue (originally just about "reserving" the `Polyform-` prefix) so that it is more precisely about the request to add the Polyform licenses to the list.

@kemitchell has submitted a PR at #903 

As mentioned above, I think the primary gating item here is the pending update to the license inclusion principles per #925. I expect the outcome of those changes will be the precursor to adding these to the list.

**Comment by swinslow** [comment] 2019-12-31 16:40
Separately, I do note that there was an open question in the PR comments for https://github.com/spdx/license-list-XML/pull/903#issuecomment-560026265:

> @heathermeeker, should the SPDX IDs for the licenses be `PolyForm-*` instead of `Polyform-*`?

**Comment by richardfontana** [comment] 2020-04-07 16:03
I do not see how the Polyform licenses meet the following element of the license inclusion guidelines:

"The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects."

**Comment by kemitchell** [comment] 2020-04-07 20:39
@richardfontana this PR long predates the new license inclusion principles. The XML files are fully baked and passing tests in #903, where, IIRC, at least one user chimed in with an example of use. There's no further load for SPDX maintainers to bear on this. Very intentionally so.

You [mentioned earlier](https://github.com/spdx/license-list-XML/pull/985#issuecomment-593732369) that you're concerned about "conferring notoriety" on licenses through SPDX. I suspect you misunderstand how Polyform sees SPDX, how SPDX sees #903, and how others see SPDX. We're not here for a referendum on Polyform, for credits or demerits. And if I took one thing away from the recent inclusion principles changes, it's that SPDX doesn't want to be a forum for that kind of thing.

Polyform folks are here because we want developers to be able to use identifiers for their choices of terms, especially in package metadata, and for analysts to the same, in structured assessments. I don't expect anyone to like our licenses just because SPDX recognized the obvious abbreviations of their titles. You'll be as free to use those shorthands to argue against the terms as others will be to choose them.

Using this reference list as a political blocker misses the point of the inclusion guidelines.

**Comment by richardfontana** [comment] 2020-04-07 21:04
@kemitchell there is evidence that one of the Polyform licenses is used by one project, of unclear significance to me. That doesn't mean that all the other Polyform licenses meet the requirement of "actual, substantial use such that [they are] likely to be encountered". I'm not sure Yugabyte's trialware is likely to be encountered either. If the "actual, substantial use" requirement is going to be meaningless then SPDX should delete it from the license inclusion principles.

**Comment by kemitchell** [comment] 2020-04-07 21:06
@richardfontana if it's going to provide cover for political objections to new licenses, it should definitely be deleted.

**Comment by jlovejoy** [comment] 2020-04-07 21:17
that requirement has been there from the beginning. The point being that SPDX aims to provide a language for exchanging information about software (and its licenses) that people use, found in the software supply chain, etc. In the early days of SPDX, we were kind of catching up to what was already out there, so this requirement was kind of obvious. 

The challenge we have now is that some license authors want to build in using the SPDX identifiers from the start - something we would want to encourage. But how to balance that with not creating identifiers for licenses that are not actually used. We discussed this quite a bit over several calls and there may have also been various comments about this. We tried to create a somewhat flexible approach that retained the original intention but provided some room for the newer scenario. NONE of those discussions had any inkling of using it as a "cover for political objections" - (and on behalf of myself and the other people who caringly engaged in those conversations, that insinuation is borderline offensive) 

If you look through the issues at licenses that have not been added and the sited reasons, I think you can see some examples - the hard part is trying to qualify why/who those licenses were not added, but a common denominator was use on one project combined with a license that was probably not needed (for various reasons) in the software world.

While this may not be helpful to the specific question at hand, hopefully it provides some context.

(Admittedly, i have not weighed in on this one yet... )

**Comment by kemitchell** [comment] 2020-04-07 21:27
@jlovejoy I don't think SPDX included that requirement to omit licenses on political grounds. How could I? We've discussed the wording and rationales for that criterion many times.

I do believe @richardfontana invokes it here for his own reasons, unrelated to materiality of the terms or any burden on SPDX maintainers. The licenses are meaningful and new. The work of prepping for identification is already done.

**Comment by jlovejoy** [comment] 2020-04-07 21:32
@kemitchell - based on this thread alone, I'm not sure I can see how the accusation against @richardfontana holds water.  I can guess that you both have some history here but let's try to leave that out, ok?

I appreciate that you are trying to design for and consider the use of SPDX identifiers in advance. That being said, you are probably a bit biased as to whether the licenses are "meaningful" (understandably)

One prior example to consider: SSPL (a license that had a certain about of "political activity" around it) was added to the SPDX License List, but not right away. A main reason for adding it was the need for being able to identify it - when it was found by scanners for example or by others. It was not the license authors who asked for it to be added (although, we did let them know, a practice that has been helpful)

**Comment by richardfontana** [comment] 2020-04-07 21:43
@kemitchell I don't have any particular political objection to Polyform that I'm conscious of (other than a general deep-rooted dislike of non-FOSS licenses). I'm supportive of SPDX inclusion of non-FOSS licenses in appropriate cases, e.g. I supported addition of SSPL which I consider non-FOSS.

**Comment by kemitchell** [comment] 2020-04-07 22:04
I don't have any grudge against @richardfontana at all, much less any I'd like to bring in here. Quite the opposite, actually.

@swinslow brought these licenses up by name in the PR on the inclusion principles, and @richardfontana responded. I do think that's part of this issue, though we split it across issue numbers:

https://github.com/spdx/license-list-XML/pull/985#issuecomment-593710979

https://github.com/spdx/license-list-XML/pull/985#issuecomment-593732369

We never had that debate. The next comment simply moved ahead to merge. And I completely understand why: that PR was nearly a month old. It's no fun waiting, be it on #985 or #903 or #885.

I'm not out for any kind of battle here. I rather hoped the new inclusion principles would make clear that SPDX identification isn't that kind of venue. Which is why I have to admit that I bristle at use of the guidelines like this, as fait accompli. Even when #903 was put on hold due to guidelines uncertainty. Even when we bothered to have a license user weigh in.  I'm comparing not just to SSPL's process, but to Blue Oak's and Parity's, as well.

If there's a new, harder rule on use in the wild, and what projects count or can be flatly dismissed, I'd be happy to contribute to a PR documenting it. If it's already been decided, perhaps on a conference call, please tell us who we need to summon in to vouch, and so how, so we can meet the requirement.

Of course you're right: I think highly of the Polyform licenses. But not mostly because they're mine. They aren't. Everyone has their pet process. But whether that happens to be Polyform's process or not, we've seen very few truly team-written, team-vetted licenses like these in the last ten years. We're not talking about any crayon terms here. We're not talking about a single-source form like SSPL or CAL or Parity. We're not talking about more patches on top of poor MIT or BSD. We're talking, for the most part, about direct analogs of well known Creative Commons forms to software source code.

**Comment by pombredanne** [comment] 2020-04-08 12:58
@kemitchell may I suggest to use instead the upcoming SPDX license id namespace feature, e.g. having your own polyform namespace?

**Comment by kemitchell** [comment] 2020-04-08 16:08
@pombredanne, @swinslow reserved the `Polyform-` prefix for us in the standard namespace [above](https://github.com/spdx/license-list-XML/issues/885#issuecomment-519612576).

Our primary motive for submission was to give project maintainers the ability to express their license choices in package metadata and other places where SPDX IDs or expressions are required or supported. I'm interested in the namespaces work as a general SPDX contributor. But I'm not aware of any packaging system supporting it.

Discussion here has gone from [expecting the new license inclusion principles to clear the way for landing the PR](https://github.com/spdx/license-list-XML/issues/885#issuecomment-569955840) to [wielding the very guidelines these licenses partially prompted against them](https://github.com/spdx/license-list-XML/issues/885#issuecomment-610474483). I'd like to work through that, one way or another, not dodge it.

**Comment by jlovejoy** [comment] 2020-04-09 17:18
@pombredanne @kemitchell - I think we need to be clear on the order of ask and answers here:
1) The Polyform licenses have been requested to be added on the SPDX License List  - we need to answer that question first.
2) IF the answer to that question is no, then the suggestion for use of the namespace option is a great one and the obvious next step.

@pombredanne - I wanted to clarify that because by mentioning the namespace option, one could infer that you are saying you don't think the Polyform licenses should be added to the SPDX License List. But I'm not sure if that was your intention? Would appreciate hearing your thoughts as to that question.

We need to answer that question first: it's not an easy one, especially given we are answering it for not 1, but 5 licenses at once. But it's also a good test of the new license inclusion guidelines!

**Comment by richardfontana** [comment] 2020-04-09 17:27
When evaluating a suite of licenses for inclusion in the SPDX license list, I think each license in the suite should stand on its own in meeting the license inclusion principles. However it could make some sense to think ahead to the eventual approval, when justified, of other licenses in the suite (for example in devising appropriate short license identifiers). 

The alternative would be that anytime you have a suite of licenses, as long as one license in the suite meets the license inclusion criteria, all the others automatically do as well. I don't see the justification. Imagine if you had a suite of 100 textually similar licenses, and only one was widely used with public source code and there was no particular reason to think the 99 others would ever see a similar level of use. 

I notice that while the SPDX list includes a large number of Creative Commons licenses, it doesn't include all the Creative Commons licenses that have ever been published.

**Comment by kemitchell** [comment] 2020-04-09 20:59
@jlovejoy thanks for setting things out. I have to admit, going from "Should we add the Polyform licenses?" to "What are the inclusion guidelines?" to "Let's update the inclusion guidelines first." right back to "What are the inclusion guidelines?" is frustrating. But there's no place like home, and I'm glad to get back where we started.

I've just pushed a version-number update to #903. In terms of technical workload, the only bit left is pushing the merge button. The rest was done nine months ago.

There's no risk of name contention, either. I'm not aware of anybody else using "Polyform" in license names, and if I were, we'd have to C&D them. Notice of allowance of our "Polyform" trademark application came through last month. The SPDX question is whether the license list will have the Polyform terms under that name, a void, or a partial void.

From a practical point of view, the license list is a big map-dictionary from string identifier to software public license text. The broadest use case, community-wide, is developers expressing their license choices in package metadata.

Polyform as an organization exists to give those developers more high-quality, standardized choices. We'd rather work through SPDX, and reinforce it, than give the packaging systems yet another reason to work around.  For what it's worth, all the lead Polyform people are also Blue Oak people, and Blue Oak has made extensive use of SPDX in every one of its [published](https://blueoakcouncil.org/list) [building](https://blueoakcouncil.org/copyleft) [blocks](https://blueoakcouncil.org/copyleft).  We're rowing together here.  We want to row together.

Part of that is transparent process.  But process is only good when it serves the point, rather than interfering with it. I admire @richardfontana's willingness to pump the brakes by any procedural lever available, as well as his willingness to come right out and say he doesn't like our kind. But the upshot is using the package managers as unwitting leverage against developer license choice. It's using SPDX as a barricade, a gatekeeper, and a pressure point, to tip the scales in a different direction.

We're not asking for gold stars for Polyform.  The same people, through Blue Oak, have [publicly deprecated a bunch of SPDX-identified licenses as ill-advised](https://blueoakcouncil.org/list#lead).  All we're asking for is neutrality.  When anyone who's commented on this issue says "Polyform Free Trial", we all know exactly which license they mean.

If the new inclusion guidelines are well and truly baked, and perhaps fleshed out further on phone calls not reflected on GitHub, please go ahead and tell me what I need to do to go about getting one, all, or several of the proposed Polyform licenses onto <https://spdx.org/licenses/licenses.json> and <https://spdx.org/licenses/> for 3.9.  Maybe that's things to do here on GitHub.  Maybe it involves a call.  Maybe both.

The team and I can make go/no-go calls from there.

**Comment by swinslow** [comment] 2020-04-22 12:50
The Polyform licenses were discussed during the SPDX legal team call on 2020-04-09. From the discussion on the call, there continued to be recognition that this is a tough call on whether to add even with the broader license inclusion principles, and viewpoints both in favor and against adding. There was also recognition that it's not necessarily an all-or-nothing decision, that all of the Polyform licenses are added or none are; the decision could be different for different ones since each is a separate license.

I had offered on the call to go through and write up my views on applying the [updated license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md#candidate-license-analysis) to the Polyform licenses. The discussion above in this thread has mainly focused on only one factor, use in the wild, but all should be considered.

I apologize that I've been delayed on this -- the chaos (life and work) of the past couple weeks has meant I've kept not getting to it. Sorry about that. In the next comment below I'll add my own thoughts, with a breakdown of the various factors. I'd encourage others to weigh in where they agree or disagree.

**Comment by swinslow** [comment] 2020-04-22 13:39
Here's my own take on applying the [updated license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md#candidate-license-analysis) to the Polyform licenses. Where applicable I'll address the different Polyform licenses separately, though many of the comments apply to them as a group.

> **Definitive factors**:

> * The submitted license must not match another license already on the SPDX License List as per the SPDX matching guidelines.

Satisfied. These are new licenses that are not currently on the list.

> * All OSI-approved licenses will be included on the SPDX License List.

Not applicable. These are not OSI-approved licenses.

> * Software licenses that apply only to executables and do not provide for the availability of the source code will not be included on the SPDX License List.

This is less clear than I'd originally been thinking. I had assumed that these were explicitly source-available licenses. However, looking at them in more detail, I see that they don't explicitly mention source code; the only reference to "source" refers to sources of funding. "Software" is defined as "the software the licensor makes available under these terms."

That said, the [license steward's web site](https://polyformproject.org) does describe these as intended to be "software source code licenses." And I understand this factor not to require that the license explicitly reference source code, but rather to exclude licenses that are _explicitly binary-only_. Given that, I think this is satisfied here.

> * The license has identifiable and stable text; it is not in the midst of drafting.

Satisfied. These have been [published with 1.0.0 version numbers](https://github.com/polyformproject/polyform-licenses/releases), and my understanding is that any future changes would be with a new version number.

> * The license steward, if any, is committed to not modifying after addition to the list and to versioning new versions in the future.

Satisfied. Same as prior comment (though @kemitchell, please weigh in if that's incorrect).

> **Other factors (roughly in order of importance)**:

Note that these are not all required to be met, rather they lean in favor of or against inclusion, in roughly the following order.

> 1. The license substantially complies with one of the following open source definitions (even if not submitted for approval or these organization have not considered the license):
> * Open Source Definition (OSD) from the Open Source Initiative (OSI)
> * Free Software Definition from the Free Software Foundation (FSF)
> * Open Source Hardware Definition from the Open Source Hardware Association (OSHWA)
> * Open Definition from the Open Knowledge Foundation
> * Free Cultural Works definition from Freedom Defined.org

Not satisfied. I don't think these would be seen as meeting the OSD (due at least to restrictions on redistribution and/or different terms for different persons / groups) or any of these other definitions.

> 2. The license is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.

Satisfied. These are explicitly structured so as to be usable by anyone as a licensor.

> 3. The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.

Leans toward not satisfied. Taking some time to look around on GitHub (including looking at the first 10 pages of Google search results for PolyForm License on github.com), I found four projects currently using PolyForm licenses:

- [yugabyte/yugabyte-db](https://github.com/yugabyte/yugabyte-db): part Apache-2.0, part Polyform-Free-Trial
- [EPPlusSoftware/EPPlus](https://github.com/EPPlusSoftware/EPPlus): Polyform-Noncommercial
- repos in the [drone](https://github.com/drone) org, e.g.:
  - [runner-go](https://github.com/drone/runner-go/blob/master/LICENSE.md): Polyform-Noncommercial OR Polyform-Small-Business OR Polyform-Free-Trial
  - [autoscaler](https://github.com/drone/autoscaler/blob/master/LICENSE.md): Polyform-Small-Business OR Polyform-Free-Trial
- [vsoch/sifweb](https://github.com/vsoch/sifweb/blob/master/LICENSE): Polyform-Noncommercial

This factor is typically the hardest one to evaluate. I'd say that with only four projects, this leans somewhat towards not being satisfied, though I also note that yugabyte-db appears to be a reasonably sizeable project (with 93 contributors, 7600 commits and 3800 stars, though there's no hard reliance on stats).

If there were a more significant number of projects willing to state that they are going to use PolyForm licenses, and they are only waiting to do so pending whether they are added to the SPDX license list, that would be relevant.

> 4. If the license does not substantively comply with one of the above open source definitions, then the license is primarily intended for free distribution of content (including, in the case of software, its source code) with limited restrictions, and meets other factors listed here.

Satisfied for Noncommercial and Small-Business; not satisfied for Strict, Free-Trial and Internal-Use.

This is actually the one that surprised me the most while going through this process. Before re-reading the licenses more closely, I had assumed that at a minimum they all permitted redistribution of the unmodified software by at least some third parties. For Noncommercial and Small-Business, that is the case, according to their Distribution License sections.

However, for Strict, Free-Trial and Internal-Use, if I understand correctly the licensee is explicitly _prohibited_ from redistributing the software. I think that makes these substantially different from every other license on the list, including the Creative Commons -NC and -ND variants. It also makes me wonder how these would be usable in a community project at all -- it seems like only the licensor is permitted to distribute the software, and anybody else would violate the license by e.g. creating even an unmodified GitHub fork of the project.

> 5. The license steward supports or is at least aware of and does not oppose its submission to the SPDX License List.

Satisfied. @kemitchell has indicated that he and the others involved with the PolyForm Project support adding these to the license list.

> The SPDX legal team will also consider any additional information considered relevant by the license steward or open source community.

This next bit is definitely meant to be just my own opinion, but I think it's relevant to note that these are clearly intended to be real licenses. I think they're well-written using clear language, as contrasted with some different submissions which are more fairly characterized as "joke" licenses. I view that as a relevant consideration in the mix here as well.

One more comment to add below, which is fully meant to be my own view of summing of all of the above.

**Comment by swinslow** [comment] 2020-04-22 13:50
Taking into account all of the factors described above, here's my _personal_ view of where it comes out. I'll stress that this is _not_ the team decision, and I'd like to see input too from others who have participated in this thread and/or are otherwise involved with the SPDX legal team.

I think that the Noncommercial and Small-Business variants can narrowly tilt in favor of being added, but Strict, Free-Trial and Internal-Use don't.

The "definitive factors" are satisfied for each of these. The "other factors" -- e.g., those that go into the "totality of the circumstances" sort of consideration, are really where it's less clear.

Since none of these substantially comply with OSD or the other listed definitions, the other factors should need to be more substantially present in order to qualify. Being drafted for general use is a big plus here; if these were otherwise the same but one-licensor-specific then I couldn't see adding them.

As discussed above, there really isn't much evidence of use in the wild at present. There's a small number of projects; to my knowledge, none of these are the license stewards' own projects, which at least helps a bit to show broader use.

Given all of that, the redistribution piece is really what makes the difference for me between the two groups. With one main underlying purpose of SPDX being to enable interchange of license information among software redistributions and supply chains, I think it's highly relevant that Strict, Free-Trial and Internal-Use appear to prohibit all redistribution altogether. For me, that pushes them over the line since I can't see how that makes them usable in a community context.

= = = = =

Okay -- I'm done.  :)  Others, please weigh in.

**Comment by jlovejoy** [comment] 2020-04-23 16:33
thanks for this write-up, @swinslow - I think this is a spot-on analysis

**Comment by swinslow** [comment] 2020-04-23 16:56
Discussed on 2020-04-23 legal team call, agreed to add Noncommercial and Small-Business for 3.9, with the others pending for reconsideration in 3.10 or future.

**Comment by swinslow** [comment] 2020-04-23 16:56
@kemitchell Could you update the current PR to reflect this? Thanks!

**Comment by kemitchell** [comment] 2020-04-23 17:29
@swinslow I'll split #903 into license-specific PRs.

**Comment by jlovejoy** [comment] 2021-02-05 17:47
Considering that we added some of these licenses already and decided not to add the others (so far), I'm going to close this. If there is a point in the future where the other licenses are requested to be reconsidered, it'd be better to have a new issue and link to this for history.

**Closed by jlovejoy** 2021-02-05 17:47 UTC
Labels: new license/exception request, new license/exception: Accepted
