### ISSUE TITLE
New license request: MIT-Argonne

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#1729] opened 2022-12-03 17:20 UTC
1. License Name: MIT Argonne
2. Short identifier: MIT-Argonne
3. License Author or steward: Unknown
4. Comments: it looks like MIT license, but it has UChicago Argonne, LLC clause.
5. License Request Url: xxx (failed due to the site crash)
6. URL(s): https://github.com/viennacl/viennacl-dev/blob/master/LICENSE
7. OSI Status: Unknown
8. Example Projects: https://github.com/viennacl/viennacl-dev/

---

Trying to create the license request on [the site](https://tools.spdx.org/app/submit_new_license/), but keep crashing after matching the license against xnet. (I can file another request later using the tool)

**Comment by goneall** [comment] 2022-12-04 04:58
> Trying to create the license request on [the site](https://tools.spdx.org/app/submit_new_license/), but keep crashing after matching the license against xnet. (I can file another request later using the tool)

@chenrui333 Please submit an issue at https://github.com/spdx/spdx-online-tools/issues with the steps to reproduce the issue

**Comment by chenrui333** [comment] 2022-12-04 19:58
> > Trying to create the license request on [the site](https://tools.spdx.org/app/submit_new_license/), but keep crashing after matching the license against xnet. (I can file another request later using the tool)
> 
> @chenrui333 Please submit an issue at https://github.com/spdx/spdx-online-tools/issues with the steps to reproduce the issue

Yeah I tried, but failed on both browsers (chrome and safari) multiple times.

**Comment by goneall** [comment] 2022-12-04 21:15
@chenrui333 - I was able to duplicate the problem.  I submitted 2 issues against the online tool:

- https://github.com/spdx/spdx-online-tools/issues/411
- https://github.com/spdx/spdx-online-tools/issues/412

**Comment by jlovejoy** [comment] 2022-12-21 23:25
This is an exact match to MIT, but adds this after the copyright notice and before the main text of the license:
"Portions of this software are copyright by UChicago Argonne, LLC.
Argonne National Laboratory, with facilities in the state of Illinois,
is owned by The United States Government, and operated by UChicago Argonne, LLC
under provision of a contract with the Department of Energy."

Which seems to me like a long-winded copyright notice. In which case, this wouldn't be a different license, but I'm not sure how to accommodate this in terms of matching??

@swinslow - thoughts?

**Comment by swinslow** [comment] 2022-12-22 23:04
@jlovejoy I tend to agree that I would view this as just the MIT license with a long-winded copyright notice. There's nothing about the additional sentences that purports to change the license terms under which the licensee can use the code.

Personally I wouldn't suggest adding markup for this, or giving it its own identifier. I think this would just be up to tools to mark as MIT or humans to conclude as MIT, and to tag that as part of the copyright notice.

**Comment by jlovejoy** [comment] 2022-12-30 05:51
@chenrui333 - this would just be MIT as per above comments

re: the submission tool issues, @goneall - looks like those have been logged otherwise, so I can close this issue?

**Comment by goneall** [comment] 2022-12-30 17:44
> re: the submission tool issues, @goneall - looks like those have been logged otherwise, so I can close this issue?

The tools issues have been logged and there is a pull request with a fix - so we don't need to keep this open to track the tools issue.

BTW - I'm just waiting for one more fix before deploying a new version of the tools.

**Comment by swinslow** [comment] 2022-12-30 18:23
Sounds good, thank you @goneall and everyone!

**Closed by swinslow** 2022-12-30 18:23 UTC
Labels: new license/exception request, new license/exception: Not Accepted
