### ISSUE TITLE
Minor typographical changes to submitted licence texts for CERN-OHL

### ISSUE THREAD

**Issue by andrewjskatz** [spdx/license-list-XML#1173] opened 2021-01-27 16:40 UTC
We have corrected a few typos in the CERN-OHL Licence texts. These versions are the versions which have been OSI approved, and the changes make no difference to the legal effect of the licences. A summary of the changes is here: https://ohwr.org/project/cernohl/issues/50 

and the revised licence texts are here:

https://ohwr.org/cern_ohl_s_v2.pdf
https://ohwr.org/cern_ohl_w_v2.pdf
https://ohwr.org/cern_ohl_p_v2.pdf

https://ohwr.org/cern_ohl_s_v2.txt
https://ohwr.org/cern_ohl_w_v2.txt
https://ohwr.org/cern_ohl_p_v2.txt

Can some kind person please update the SPDX versions of the text, and, where appropriate, add a note to say that the licence texts have been slightly altered to correct typos, in line with the summary linked above?

Thanks

Andrew

**Comment by jlovejoy** [comment] 2021-02-05 06:08
Thanks @andrewjskatz 
legal team: looking at the changes as summarized in the issues link above, I think they are non-substantive and can/should be dealt with via markup. But could use some eyeballs to check that and how to implement.
@swinslow - thoughts?

**Comment by swinslow** [comment] 2021-02-28 22:09
Agree, I'm +1 on making these changes via markup to the existing templates.

**Comment by jlovejoy** [comment] 2021-05-05 00:27
did this ever get done? I don't think it did... we had PRs to add the OSI-approved tag which @emmanueltournier completed, but I think we were treating this separately?

**Comment by swinslow** [comment] 2021-05-13 16:52
I'll make the changes on this before pushing the 3.13 release.

**Comment by swinslow** [comment] 2021-05-15 22:45
Hi @andrewjskatz (and cc @jlovejoy), I was about to put together a PR to add markup for these items. However, looking at them more closely from https://ohwr.org/project/cernohl/issues/50, I think a few of them don't need changes (per the SPDX matching guidelines) and the remaining one presents a problem I'm describing below.

From the link above, here are the items I see that have changed in the license texts:

> In the patent section (S-7.1, W-7.1, P-6.1), the spelling of “licence” seems inconsistent:
> … patent license to Make, … where such licence applies …

Under the [SPDX matching guidelines (see section 8)](https://spdx.dev/license-list/matching-guidelines/) and the related [equivalent words list](https://github.com/spdx/license-list-XML/blob/master/equivalentwords.txt), "license" and "licence" are considered to be equivalent, and templates do not contain markup for this guideline. So I think this is already okay as-is.

> In P-1.5, the lines are not vertically aligned.
> In W-1.7 and W-1.8, the sub-enumeration (a, b) is missing an indentation.
> All other sub-enumerations are indented by 1 space (e.g. W-1.2, S-1.7)."

Similarly, under the matching guidelines (see section 3) amount of whitespace isn't relevant for matching purposes, and the templates do not include markup for this. (I have a feeling any whitespace markup would just fall out of the XML files anyway...)

> In section P-3.3, the sub-enumeration starts after “You” (consistent with other variants).
> In section P-3.4, it starts before “You”:
> 3.3
> … provided that You:
> a) retain …
> 
> 3.4
> … provided that:
> a) You comply …

So, this does warrant markup to handle the different versions. The problem is, getting into the nitpicky details, I'm frankly not sure how to apply the markup to handle both cases.

Ideally what you want to do is to say that "You" should appear _either_ in the first line, _or if it isn't there_ then in the nested bullets. The problem is that I'm not sure the license list markup schema is rich enough to encode this. It might be, but if so then I'm not sure how. @goneall may have thoughts on this, though I know he is traveling and won't be available for a while.

One approach could be just to mark "You" optional in each one. That would make it match regardless of where the "You" appears. But it would also match if "You" appears in both places, or in none of them. If you're okay with that, then I might suggest this as how to handle it, though it's not ideal and leads to matching some nonsensical variations.

Or, we could skip markup altogether and just change the text to the new version. If we do that, though, then it'll stop matching anyone who has used the _old_ version.

Given the above, I'm going to leave this issue open, but will move it to 3.14 so that you can let us know your thoughts on this issue (and since I'm pushing the 3.13 release very shortly). Happy to get it merged early in 3.14 if you are okay with the approach mentioned above.

**Comment by swinslow** [comment] 2021-06-10 15:43
Hi @andrewjskatz, wanted to circle back on your thoughts about my comment [above](https://github.com/spdx/license-list-XML/issues/1173#issuecomment-841735467). Thanks!

**Comment by swinslow** [comment] 2021-08-05 16:43
Hi @andrewjskatz, circling back, do you have any thoughts on the comments above?

**Comment by swinslow** [comment] 2022-01-19 23:08
Hi @andrewjskatz, checking back, do you have any thoughts on my comments [above](https://github.com/spdx/license-list-XML/issues/1173#issuecomment-841735467)? If not, we may close this issue for the time being.

**Comment by swinslow** [comment] 2022-02-06 20:22
Closing this issue for now. @andrewjskatz, if you get a chance to weigh in on the earlier comments, feel free to re-open and we can discuss how best to handle this.

**Closed by swinslow** 2022-02-06 20:22 UTC
Labels: new license/exception: waiting for submitter, XML markup change
