### ISSUE TITLE
New license request: SchemeReport [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by samth** [spdx/license-list-XML#1340] opened 2021-10-14 03:18 UTC
**1.** License Name: Scheme Report License
**2.** Short identifier: SchemeReport
**3.** License Author or steward: Probably written by William Clinger
**4.** Comments: This license has been used for the Scheme standard reports since the Revised Revised Report on Scheme in 1985, up through the most recent R7RS. It was likely the source of the Haskell Report License, with which it shares substantial text. I would like to have this available as an SPDX identifier. It is unlikely that this license will be used for other things than the Scheme Reports, except in so far as the text of those reports is used for other documents, as the license suggests.
**5.** Standard License Header: n/a
**6.** License Request Url: http://tools.spdx.org/app/license_requests/126
**7.** URL(s): https://schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-3.html#%_sec_Temp_4
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://dspace.mit.edu/bitstream/handle/1721.1/5600/AIM-848.pdf?sequence=2&isAllowed=y, https://github.com/racket/r6rs/blob/master/r6rs-doc/, https://small.r7rs.org/attachment/r7rs.pdf

**Comment by jlovejoy** [comment] 2021-11-11 03:10
thanks @samth - sorry for missing that.
copying text here: 
"We intend this report to belong to the entire Scheme community, and so we grant permission to copy it in whole or in part without fee. In particular, we encourage implementors of Scheme to use this report as a starting point for manuals and other documentation, modifying it as necessary."

here is a analysis based on our license inclusion principles (next comment)

**Comment by jlovejoy** [comment] 2021-11-11 03:22
* Has the license been approved by the OSI?
  * no
* Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?
  * it does not match anything currently on the SPDX License List
* If a software license, does it apply to source code and not only to executables?
  * it refers to a report (not software) 
* Does the license have identifiable and stable text, and is not in the midst of drafting?
  * seems stable, yes
* Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?
  * not sure this is relevant, as it seems this is a one-off 

Other factors for inclusion
1. Does the license substantially comply with one of the free/open content definitions?
yes
2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
it has been in use for a long time, not sure how widespread it use is beyond the example cited here or how it being on the SPDX License List would help in identification given the text is usually incorporated in a paper? 

3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?
it seem specific to these reports, probably not used otherwise

4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?
yes

5. Does the license steward support this submission, or is at least aware of and not in opposition of it?
not sure, probably doesn't matter for something this old

Summary of factors / outcome
I'm a bit torn here, as to the prevalence of use and how it is used in terms of the application of items on the SPDX License List.
@samth - can you provide a bit more color as to how having an SPDX identifier for this would be helpful for context

will discuss further with SPDX legal

**Comment by samth** [comment] 2021-11-11 04:15
We came upon this issue while adding SPDX identifiers for the licenses of Racket packages, some of which include the text of, or text from, the Scheme reports. Adding it would make it possible to make these machine-processable. 

An alternative that would work equally well would be to broaden the HaskellReport license identifier to include this one as well. That one is almost certainly derived from the text in the Scheme report and serves identical purposes.

**Comment by LiberalArtist** [comment] 2021-11-11 19:00
Re <https://github.com/spdx/license-list-XML/issues/1340#issuecomment-965954420>:
>  -  If a software license, does it apply to source code and not only to executables?
>      -  it refers to a report (not software)

It may be relevant that the Scheme reports, which serve as the standards for the Scheme programming language, include source code, not just prose. For example, [Appendix B: Sample definitions for derived forms](http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-16.html#node_chap_B) of R6RS (2007) includes the following reference implementation for Scheme's `case` form, which could be used—directly or with modifications—by Scheme implementations that don't handle `case` as a compiler built-in:
```scheme
(define-syntax case
  (syntax-rules (else)
    ((case expr0
       ((key ...) res1 res2 ...)
       ...
       (else else-res1 else-res2 ...))
     (let ((tmp expr0))
       (cond
         ((memv tmp '(key ...)) res1 res2 ...)
         ...
         (else else-res1 else-res2 ...))))
    ((case expr0
       ((keya ...) res1a res2a ...)
       ((keyb ...) res1b res2b ...)
       ...)
     (let ((tmp expr0))
       (cond
         ((memv tmp '(keya ...)) res1a res2a ...)
         ((memv tmp '(keyb ...)) res1b res2b ...)
         ...)))))
```

**Comment by LiberalArtist** [comment] 2021-11-11 19:43
Another example of the license in use is [`Scheme->C`](https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/scheme/impl/scheme2c/0.html), a Scheme to C compiler by Joel Bartlett for DEC and HP. From the copyright file for the [Debian "sid" package `scheme2c-doc`](https://salsa.debian.org/debian/scheme2c/-/blob/1a34dc8a1c21418f82461594abc20cc9f869e72b/debian/copyright#L60-84):
```
The documentation includes a copy of the R4RS manual, which states:

  We intend this report to belong to the entire Scheme community, and
  so we grant permission to copy it in whole or in part without fee.
  In particular, we encourage implementors of Scheme to use this
  report as a starting point for manuals and other documentation,
  modifying it as necessary.

  It was written and edited by:

    William Clinger and Jonathan Rees (Editors)

    H. Abelson       R. K. Dybvig     C. T. Haynes    G. J. Rozas
    N. I. Adams IV   D. P. Friedman   E. Kohlbecker   G. L. Steele Jr.
    D. H. Bartley    R. Halstead      D. Oxley        G. J. Sussman
    G. Brooks        C. Hanson        K. M. Pitman    M. Wand

The R4RS sources include a LaTeX style file, algol60.sty, which states

  % Copyright (C) 1985 by Leslie Lamport
  % Hacked To Death (H) 1986 by Jonathan Rees from Lamport's REPORT and
  %   REP11 document styles

This style file appears to be covered by the same permissive grant
that covers the remainder of the R4RS manual LaTeX source.
```

**Comment by jlovejoy** [comment] 2021-11-14 17:53
I'm ok with adding this

other thoughts?
@swinslow @seabass-labrax @johnmhoran ??

**Comment by swinslow** [comment] 2021-11-15 14:23
Thanks all -- I'm +1 to add this. Agree with all of @jlovejoy's comments in her [analysis above](https://github.com/spdx/license-list-XML/issues/1340#issuecomment-965954420), and given the cited usage in actual Scheme packages I think it makes sense to add it.

**Comment by swinslow** [comment] 2021-11-15 14:26
I meant to mention also -- I do think it should be added as a separate identifier, rather than expanding [`HaskellReport`](https://spdx.org/licenses/HaskellReport.html) to include it.

The `HaskellReport` license includes a requirement that the report be "reproduced in its entirety", whereas this `SchemeReport` license permits copying "in whole or in part". So even though they might have had a common origin, I think they're substantially different in effect and should get separate identifiers.

**Comment by johnmhoran** [comment] 2021-11-15 16:29
I agree with @jlovejoy and @swinslow .  👍

**Comment by seabass-labrax** [comment] 2021-11-15 20:13
@jlovejoy, I might be a little biased since I'm such a big Scheme fan :D

I think @samth and @LiberalArtist are doing great work with adding the machine readable licensing information, and that it demonstrate the license's substantial use well. My initial concern was that the language in `SchemeReport` wasn't very assertive, but after just shy of 50 years I think it has proved itself as a true license!

I looked at the `HaskellReport` text and I would agree with @swinslow as to having a separate identifier.

PS. I like the way you snuck a macro into a licensing discussion, @LiberalArtist; I'll have to try that one myself in future ;)

**Comment by jlovejoy** [comment] 2021-11-15 23:43
@swinslow @seabass-labrax - agreed on a new license, not trying to mark up HaskellReport (meant to say that before)

**Comment by jlovejoy** [comment] 2021-11-15 23:44
marked as approved! @samth - would you be able to prepare the PR to add this? 

new license workflow documented at https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md

**Comment by samth** [comment] 2021-11-16 14:51
I'll do that.

**Closed** 2021-11-17 01:06 UTC
Labels: new license/exception request, new license/exception: Accepted
