### ISSUE TITLE
GPL-2.0(*) templates: var text to handle variation in FSF address formatting?

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#1972] opened 2023-05-16 17:12 UTC
In [this GPL-2.0 license text](https://github.com/javaee/javamail/blob/master/LICENSE.txt#L369-L371), the FSF's address has been split across multiple lines, and 2 comma characters (`,`) removed, which means that matching of this text via the various GPL-2.0(*) templates fails.  This was originally discovered in [this Spdx-Java-Library issue](https://github.com/spdx/Spdx-Java-Library/issues/166).

In that issue, @goneall suggested that variations in this section of the license text could be handled in the GPL-2.0(*) templates via the addition of `<var>` elements.

**Comment by jlovejoy** [comment] 2023-05-17 19:26
hi @pmonks - so... white space (ie., split across multiple lines) shouldn't matter as per B.4 https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/

However, punctuation does matter (see B.6). So, would this mean we'd be adding markup just for the commas?

**Comment by goneall** [comment] 2023-05-17 21:29
@jlovejoy Just to clarify - the issue is with the matching regular expression in the license XML - this will need to be fixed for matches to occur.  In other words, there is an `<alt` tag with a match regular expression that assumes the text it is matching is in the same line - which is a bad assumption.

**Comment by jlovejoy** [comment] 2023-05-19 03:00
@goneall hmmm... so that could be a problem with any license that has an <alt> tag, then?

**Comment by goneall** [comment] 2023-05-19 19:53
> so that could be a problem with any license that has an tag, then?

@jlovejoy it has to do with that is in the `match="..."` string - I don't think this will be an issue for most of the licenses since they typically use `.+` which will match line feeds.

**Comment by jlovejoy** [comment] 2023-06-01 20:11
thanks @goneall - so... is there a PR needed here?

**Comment by goneall** [comment] 2023-06-02 02:45
> so... is there a PR needed here?

Yes - a change to the regex to allow for line feeds.  Personally, I would just do a `.{X,Y}` where X is the minimum number of characters for a match and `Y` is the maximum number of character for a match rather than the specific text.

**Comment by jlovejoy** [comment] 2024-01-02 22:04
similar to #2279 - will let @goneall approve!

**Comment by goneall** [comment] 2024-01-03 03:43
Resolved with #2279

**Closed by goneall** 2024-01-03 03:43 UTC
Labels: XML markup change
