### ISSUE TITLE
Record the licenses to which an exception may apply

### ISSUE THREAD

**Issue by waynebeaton** [spdx/license-list-XML#1457] opened 2022-05-09 19:47 UTC
Moved from https://github.com/spdx/LicenseListPublisher/issues/132

I'm approaching this from the perspective of trying to make a best guess determination of the SPDX License Identifier from the results of `scancode-toolkit`. In the absence of an explicit tag, scancode does a fantastic job of identifying the various licenses, but doesn't necessary know how they combine.

In the case where a license and an exception are identified by the scanner, it's relatively easy to stitch the two together using `with`. It's less easy to guess whether two licenses identified by the scanner are combined via conjunction or disjunction, but we can at least automate creating a consistent SPDX identifier.

In the case where content is multiply licensed and an exception is involved, we can guess to which license the exception belongs, but the guess could be made better if we have a means of identifying to which license an exception _likely_ belongs.

That is, if scancode detects `Apache-2.0`, `GPL-2.0-only`, and `Classpath-exception-2.0` in content that does not include an SPDX-License-Identifer tag that might otherwise tell us how these are combined, we could reasonably guess that the license might be `Apache-2.0 and GPL-2.0-only with Classpath-exception-2.0` and not `Apache-2.0 with Classpath-exception-2.0 and GPL-2.0-only`  (whether or not `and` is right is a toss up, but we can make a reasonable assumption that the classpath exception applies to the GPL).

This specific example feels pretty obvious, but I don't know enough about most of the exceptions to understand whether or not this is something that can be reasonably done consistently by adding a bit of extra metadata.

This is part of a class of problem that I assume others are thinking about, e.g., how to combine and collapse licenses (`GPL-2.0-only and GPL-2.0-or-later` can collapse to `GPL-2.0-only`, or `GPL-2.0-only+` is basically the same as `GPL-2.0-or-later`). Is that discussion happening somewhere?

/cc @goneall @swinslow @zvr

**Comment by zvr** [comment] 2022-05-10 08:07
I am not against recording such information (where possible), but I fail to understand the use case.

It seems you're saying that some texts get recognized and you want to construct a valid (and correct) SPDX License Expression. Let's forget exceptions for a moment: if you "detect" `License-1` and `License-2`, how do you know whether the correct expression is `License-1 OR License-2` or `License-1 AND License-2` ?

**Comment by swinslow** [comment] 2022-05-10 15:45
Thanks for raising this for discussion @waynebeaton! 

Like @zvr, I'm also not opposed to recording such information in a more standardized way. We do already end up often collecting this info in non-structured text in the Notes section (e.g. [FLTK-exception](https://spdx.org/licenses/FLTK-exception.html), [Autoconf-exception-2.0](https://spdx.org/licenses/Autoconf-exception-2.0.html), [SHL-2.0](https://spdx.org/licenses/SHL-2.0.html)).

I could see value in having a separate structured field (presumably an optional list of one or more license identifiers) that it's generally intended to be used with. I think if it's added, it should be with the understanding that SPDX isn't opining on whether or not that's a complete list, rather that it's the set of license(s) that are generally understood as those which the exception is typically used with.

That said, I also share @zvr's concerns about not having SPDX itself get too far into making recommendations or guidance on the "how do we combine license findings into a single license expression?" discussion. I view SPDX's role as a project as focused on defining the grammar and substance around license identifiers and expressions. SPDX can act as an "upstream" project for other separate "downstream" efforts that want to make recommendations around that sort of thing, and that's great, I'd just say that's probably out of scope for the SPDX project itself.

**Comment by waynebeaton** [comment] 2022-05-10 20:11
> Let's forget exceptions for a moment: if you "detect" `License-1` and `License-2`, how do you know whether the correct expression is `License-1 OR License-2` or `License-1 AND License-2` ?

I don't. I'm not trying to solve this problem. 

In this sort of case, my strategy is for the automation to assume the more restrictive option (AND) and send the results to my intellectual property analyst to make the call.

If my tools detect `License-1` and `Exception-1`, my experience has been that I can assume that the correct expression is `License-1 with Exception-1` and reasonably conclude the license without engaging my relatively expensive (yet affable) intellectual property analyst.

When my tools detect `License-1`, `License-2`, and `Exception-1`, I can only guess with which license the exception is associated. I've currently got a little hack set up that helps me make a good guess in a small number of common cases. But now I need to expand this to cover more cases. If I'm going to do this, I figure that I should share and putting it close to source makes sense to me.

While I could probably argue the grey area of whether or not this falls into the category of "just the facts" or "recommendation", my sense is that this aligns more with the former.

If the answer is that this is better explored elsewhere, I can do that. If anybody has a pointer, that'd also be an awesome outcome of this discussion.

**Comment by swinslow** [comment] 2022-05-10 22:23
Thanks @waynebeaton, this is helpful context.

Personally my thoughts are that it would be useful, at a minimum, for the SPDX License List to have "this exception is intended for use with these licenses" in a structured field rather than unstructured "Notes" text. And beyond that, users of the License List can make use of that field in whatever way seems appropriate to them.

In your case, would that address the problem you're looking to solve in your tools, if the exceptions were set up in that way?

Also interested in hearing thoughts from other SPDX legal team participants...

**Comment by jlovejoy** [comment] 2022-07-30 18:13
Just reviewing old issues and not sure where this landed. If there is still interest, then this seems like a more formal "change proposal" would be helpful to define what the issue is, why this needs to be solved, how this fits in the SPDX vision/mission, and possible solutions, etc. That might be easier done via the legal team email list? I'll leave this open for a bit to see if there is a response as to interest to take this forward and lead on it

**Comment by jlovejoy** [comment] 2023-04-14 21:37
closing as there has been no further comments here, so I'm presuming the answer to my question above is that the interest has waned. If this is something someone wants to carry forward, then the Change Proposal process and repo would be a good route

**Closed by jlovejoy** 2023-04-14 21:37 UTC
Labels: XML schema change
