### ISSUE TITLE
New license request: mplus [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1407] opened 2022-02-02 03:06 UTC
**1.** License Name: mplus Font License
**2.** Short identifier: mplus
**3.** License Author or steward: ?
**4.** Comments: this is a "good" font license for Fedora and is used in a handful of packages in the current Fedora release
**5.** Standard License Header: none
**6.** License Request Url: http://tools.spdx.org/app/license_requests/142
**7.** URL(s): https://fedoraproject.org/wiki/Licensing:Mplus?rd=Licensing/mplus
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourcegraph.com/search?q=context:global+r:src.fedoraproject.org+file:.*%5C.spec%24+%5ELicense:%5Cs%2B.*mplus+TIMEOUT:120s&patternType=regexp

**Comment by swinslow** [comment] 2022-02-09 13:44
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No (not to my knowledge)

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes

### If a software license, does it apply to source code and not only to executables?

N/A, not a software license

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, historical license which doesn't appear to be in midst of drafting

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

To the extent that there is a "license steward" for this one, it might be the author of the M+ Fonts -- see [wikipedia page](https://en.wikipedia.org/wiki/M%2B_FONTS). If so, note that it appears that they have moved to using [OFL-1.1 instead](https://mplusfonts.github.io/#license) for the M+ Fonts themselves, so probably unlikely to be modifying this further.

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

Yes - this is a short, informal license specific to fonts that appears to permit full use / reproduction / distribution, with modifications and for any purpose.

### 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one significant project satisfies this*

Appears to be used for several fonts beyond M+, including those distributed as part of Fedora

### 3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

Yes

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

Probably not aware, see above re: license author

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

+1 to add, this appears to be a clearly "free content" license for fonts and has sufficient use as a historical license to warrant inclusion.

**Comment by capfei** [comment] 2022-02-24 17:22
+1 to add

**Comment by johnmhoran** [comment] 2022-02-24 17:22
+1

**Comment by swinslow** [comment] 2022-02-24 17:22
Discussed on 2022-02-24 legal team call, agreed to add.

**Comment by jlovejoy** [comment] 2022-03-10 02:26
PR made #1420

**Comment by swinslow** [comment] 2022-03-10 15:32
Merged #1420; closing this issue

**Closed by swinslow** 2022-03-10 15:32 UTC
Labels: new license/exception request, new license/exception: Accepted
